# TUGAS DATA MINING 3

In [42]:
import numpy as np
import pandas as pd

In [43]:
insurance = pd.read_csv('G:\Kuliah\Data Mining\Transformasi Data\Tugas\insurancefix.csv')
insurance.head()

age     bmi      charges
0  19.0  27.900  16884.92400
1  18.0  33.770   1725.55230
2  28.0  33.000   4449.46200
3   NaN  22.705  21984.47061
4  32.0  28.880   3866.85520

In [44]:
insurance.describe()

age         bmi       charges
count  315.000000  304.000000    330.000000
mean    40.063492   30.743964  13698.153359
std     14.474305    5.632816  12380.939002
min     18.000000   15.960000   1137.011000
25%     28.000000   26.730000   4828.586213
50%     40.000000   30.250000   9621.791225
75%     53.000000   34.777500  17637.453087
max     64.000000   49.060000  51194.559140

In [45]:
np.sum(insurance.isnull())

age        33
bmi        44
charges    18
dtype: int64

In [46]:
insurance['age'] = insurance['age'].fillna((insurance['age'].mean()))
insurance['bmi'] = insurance['bmi'].fillna((insurance['bmi'].mean()))
insurance['charges'] = insurance['charges'].fillna((insurance['charges'].mean()))

np.sum(insurance.isnull())

age        0
bmi        0
charges    0
dtype: int64

In [47]:
insurance.tail()

age        bmi      charges
343  63.000000  36.765000  13981.85035
344  49.000000  30.743964  10977.20630
345  40.063492  29.260000   6184.29940
346  33.000000  35.750000   4889.99950
347  46.000000  33.345000   8334.45755

In [48]:
insurance.to_excel("insurance_no_missing.xlsx")

In [49]:
from scipy import stats
z = np.abs(stats.zscore(insurance._get_numeric_data()))
print(z)
insurance = insurance[(z < 3).all(axis=1)]
print(insurance.shape)

[[1.53199535e+00 5.41086605e-01 2.64721306e-01]
 [1.60472761e+00 5.75727313e-01 9.94549952e-01]
 [8.77405022e-01 4.29228724e-01 7.68277962e-01]
 ...
 [5.16793779e-16 2.82335851e-01 6.24167051e-01]
 [5.13743730e-01 9.52437970e-01 7.31683028e-01]
 [4.31775629e-01 4.94867702e-01 4.45555931e-01]]
(345, 3)


In [50]:
insurance.to_excel("insurance_no_missing+out.xlsx")

In [57]:
insurance_no_missing = pd.read_csv('G:\Kuliah\Data Mining\Transformasi Data\Tugas\insurance_no_missing.csv')
insurance_no_missing.tail()

Unnamed: 0        age        bmi      charges
343         343  63.000000  36.765000  13981.85035
344         344  49.000000  30.743964  10977.20630
345         345  40.063492  29.260000   6184.29940
346         346  33.000000  35.750000   4889.99950
347         347  46.000000  33.345000   8334.45755

In [58]:
x = insurance_no_missing.iloc[0:348,1:4]
x.tail()

age        bmi      charges
343  63.000000  36.765000  13981.85035
344  49.000000  30.743964  10977.20630
345  40.063492  29.260000   6184.29940
346  33.000000  35.750000   4889.99950
347  46.000000  33.345000   8334.45755

In [59]:
from sklearn.preprocessing import normalize
xnorm = normalize(x,norm='l2')
xnorm = pd.DataFrame(xnorm)
xnorm.tail()

0         1         2
343  0.004506  0.002629  0.999986
344  0.004464  0.002801  0.999986
345  0.006478  0.004731  0.999968
346  0.006748  0.007310  0.999951
347  0.005519  0.004001  0.999977

In [60]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=0)
xsoft = softmax(xnorm)
xsoft = pd.DataFrame(xsoft)
print(xsoft)

            0         1         2
0    0.002862  0.002864  0.002874
1    0.002889  0.002916  0.002873
2    0.002877  0.002881  0.002874
3    0.002864  0.002863  0.002874
4    0.002882  0.002881  0.002874
5    0.002882  0.002879  0.002874
6    0.002875  0.002871  0.002874
7    0.002873  0.002870  0.002874
8    0.002866  0.002866  0.002874
9    0.002865  0.002862  0.002874
10   0.002885  0.002887  0.002873
11   0.002865  0.002862  0.002874
12   0.002895  0.002914  0.002873
13   0.002873  0.002870  0.002874
14   0.002864  0.002868  0.002874
15   0.002888  0.002898  0.002873
16   0.002873  0.002868  0.002874
17   0.002886  0.002888  0.002873
18   0.002874  0.002870  0.002874
19   0.002861  0.002862  0.002874
20   0.002872  0.002867  0.002874
21   0.002879  0.002882  0.002874
22   0.002904  0.002947  0.002872
23   0.002862  0.002862  0.002874
24   0.002876  0.002873  0.002874
25   0.002871  0.002865  0.002874
26   0.002871  0.002864  0.002874
27   0.002872  0.002867  0.002874
28   0.002883 

In [66]:
xsoft.to_excel("insurance_no_missing+transformasi.xlsx")

In [61]:
insurance_no_missing_out = pd.read_csv('G:\Kuliah\Data Mining\Transformasi Data\Tugas\insurance_no_missing+out.csv')
insurance_no_missing_out.tail()

Unnamed: 0        age        bmi      charges
340         343  63.000000  36.765000  13981.85035
341         344  49.000000  30.743964  10977.20630
342         345  40.063492  29.260000   6184.29940
343         346  33.000000  35.750000   4889.99950
344         347  46.000000  33.345000   8334.45755

In [63]:
y = insurance_no_missing.iloc[0:345,1:4]
y.tail()

age        bmi      charges
340  24.0  27.600000  18955.22017
341  62.0  30.020000  13352.09980
342  60.0  27.550000  13217.09450
343  63.0  36.765000  13981.85035
344  49.0  30.743964  10977.20630

In [64]:
from sklearn.preprocessing import normalize
ynorm = normalize(y,norm='l2')
ynorm = pd.DataFrame(ynorm)
ynorm.tail()

0         1         2
340  0.001266  0.001456  0.999998
341  0.004643  0.002248  0.999987
342  0.004540  0.002084  0.999988
343  0.004506  0.002629  0.999986
344  0.004464  0.002801  0.999986

In [65]:
ysigmoidal = (1-2.718281828**(-ynorm))/(1+2.718281828**(-ynorm))
ysigmoidal = pd.DataFrame(ysigmoidal)
ysigmoidal.tail()

0         1         2
340  0.000633  0.000728  0.462116
341  0.002322  0.001124  0.462112
342  0.002270  0.001042  0.462112
343  0.002253  0.001315  0.462112
344  0.002232  0.001400  0.462112

In [68]:
ysigmoidal.to_excel("insurance_no_missing+out+transformasi.xlsx")