# TUGAS PRE-PROCESSING DATA

In [31]:
import pandas as pd
import numpy as np

In [32]:
nfa = pd.read_csv(r'G:\Kuliah\Data Mining\Pre-processing Data\Tugas\NFA 2018.csv')
nfa.head()

country UN_region  UN_subregion           record     crop_land  \
0  Armenia      Asia  Western Asia     BiocapPerCap  1.611286e-01   
1  Armenia      Asia  Western Asia     BiocapTotGHA  5.558130e+05   
2  Armenia      Asia  Western Asia     EFConsPerCap  3.909225e-01   
3  Armenia      Asia  Western Asia     EFConsTotGHA  1.348487e+06   
4  Armenia      Asia  Western Asia  EFExportsPerCap  1.124910e-03   

    grazing_land    forest_land  fishing_ground  built_up_land        carbon  \
0       0.135023       0.083836        0.013718       0.033669  0.000000e+00   
1  465763.337400  289190.662300    47320.224590  116139.598200  0.000000e+00   
2       0.189137       0.000001        0.004138       0.033669  1.112225e+00   
3  652429.066600       4.327841    14272.803690  116139.598200  3.836620e+06   
4       0.002283       0.000000        0.000438       0.000000  4.819043e-02   

          total  Percapita GDP (2010 USD)  population  
0  4.273741e-01                   949.033     3449000  
1  1.474227e+06                   949.033     3449000  
2  1.730092e+00                   949.033     3449000  
3  5.967954e+06                   949.033     3449000  
4  5.203676e-02                   949.033     3449000

In [33]:
nfa.describe()

crop_land  grazing_land   forest_land  fishing_ground  \
count  6.353000e+04  6.353000e+04  6.353000e+04    6.353000e+04   
mean   1.465068e+07  6.324612e+06  1.531334e+07    3.576364e+06   
std    1.445766e+08  6.237420e+07  1.798437e+08    3.905889e+07   
min    0.000000e+00  0.000000e+00  0.000000e+00    0.000000e+00   
25%    3.027605e-01  7.470049e-02  1.508091e-01    3.252735e-02   
50%    2.841671e+00  2.526463e+00  3.110603e+00    3.670478e+00   
75%    2.027347e+06  6.580112e+05  1.497303e+06    2.436509e+05   
max    3.996304e+09  1.576582e+09  5.496461e+09    1.127790e+09   

       built_up_land        carbon         total  Percapita GDP (2010 USD)  \
count   6.353000e+04  6.353000e+04  8.702000e+04              71410.000000   
mean    1.311909e+06  2.591459e+07  5.217695e+07              10129.722779   
std     1.448057e+07  3.448775e+08  5.890184e+08              15646.206882   
min     0.000000e+00  0.000000e+00  5.150000e-05                115.794000   
25%     0.000000e+00  1.946352e-02  1.313131e+00                988.470000   
50%     3.247780e-02  1.293047e+00  1.858845e+02               3153.740000   
75%     5.794159e+04  9.168465e+05  7.792829e+06              11972.100000   
max     4.649979e+08  1.251963e+10  2.060191e+10             113682.000000   

         population  
count  8.702000e+04  
mean   6.305956e+07  
std    4.264394e+08  
min    5.000000e+03  
25%    2.001000e+06  
50%    6.632500e+06  
75%    2.056300e+07  
max    7.265786e+09

In [34]:
np.sum(nfa.isnull())

country                         0
UN_region                       0
UN_subregion                    0
record                          0
crop_land                   23490
grazing_land                23490
forest_land                 23490
fishing_ground              23490
built_up_land               23490
carbon                      23490
total                           0
Percapita GDP (2010 USD)    15610
population                      0
dtype: int64

In [36]:
nfa['crop_land'] = nfa['crop_land'].fillna((nfa['crop_land'].mean()))
nfa['grazing_land'] = nfa['grazing_land'].fillna((nfa['grazing_land'].mean()))
nfa['forest_land'] = nfa['forest_land'].fillna((nfa['forest_land'].mean()))
nfa['fishing_ground'] = nfa['fishing_ground'].fillna((nfa['fishing_ground'].mean()))
nfa['built_up_land'] = nfa['built_up_land'].fillna((nfa['built_up_land'].mean()))
nfa['carbon'] = nfa['carbon'].fillna((nfa['carbon'].mean()))
nfa['Percapita GDP (2010 USD)'] = nfa['Percapita GDP (2010 USD)'].fillna((nfa['Percapita GDP (2010 USD)'].mean()))

np.sum(nfa.isnull())

country                     0
UN_region                   0
UN_subregion                0
record                      0
crop_land                   0
grazing_land                0
forest_land                 0
fishing_ground              0
built_up_land               0
carbon                      0
total                       0
Percapita GDP (2010 USD)    0
population                  0
dtype: int64

In [38]:
from scipy.stats import mode
from scipy import stats

z = np.abs(stats.zscore(nfa._get_numeric_data()))
print(z)
nfa = nfa[(z < 3).all(axis=1)]
print(nfa.shape)

[[0.11859966 0.11867313 0.09965482 ... 0.08858339 0.6477379  0.1397875 ]
 [0.11410027 0.10993369 0.09777285 ... 0.08608053 0.6477379  0.1397875 ]
 [0.11859966 0.11867313 0.09965482 ... 0.08858339 0.6477379  0.1397875 ]
 ...
 [0.11511879 0.1143766  0.09333888 ... 0.07301561 5.45996923 0.14682957]
 [0.11859966 0.11867313 0.09965482 ... 0.08858338 5.45996923 0.14682957]
 [0.11680907 0.11789077 0.09835322 ... 0.08298341 5.45996923 0.14682957]]
(83853, 13)
