# LATIHAN PRE-PROCESSING DATA

In [53]:
import pandas as pd
import numpy as np

sydney = pd.read_csv('G:\Kuliah\Data Mining\Praktikum\Pre-Processing Data\Data Sydney.csv')
sydney.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  1/2/2008   Sydney     19.5     22.4      15.6          6.2       0.0   
1  2/2/2008   Sydney     19.5     25.6       6.0          3.4       2.7   
2  3/2/2008   Sydney     21.6     24.5       6.6          2.4       0.1   
3  4/2/2008   Sydney     20.2     22.8      18.8          2.2       0.0   
4  5/2/2008   Sydney     19.7     25.7      77.4          0.0      11.0   

   WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
0          17.0          20.0         92.0         84.0       1017.6   
1           9.0          13.0         83.0         73.0       1017.9   
2          17.0           2.0         88.0         86.0       1016.7   
3          22.0          20.0         83.0         90.0       1014.2   
4           6.0          88.0         74.0       1008.3       1004.8   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RISK_MM  
0       1017.4       8.0       8.0     20.7     20.9      6.0  
1       1016.4       7.0       7.0     22.4     24.8      6.6  
2       1015.6       7.0       8.0     23.5     23.0     18.8  
3       1011.8       8.0       8.0     21.4     20.9     77.4  
4          8.0       8.0      22.5     25.5      1.6      NaN

In [54]:
sydney.describe()

MinTemp      MaxTemp     Rainfall  Evaporation     Sunshine  \
count  3344.000000  3344.000000  3344.000000  3344.000000  3344.000000   
mean     14.869587    22.977961     3.341597     5.197996     7.504844   
std       4.562860     4.545436     9.874956     2.864817     4.453951   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%      11.000000    19.600000     0.000000     3.200000     4.400000   
50%      14.900000    22.800000     0.000000     4.800000     8.400000   
75%      18.800000    26.000000     1.400000     7.000000    10.300000   
max      27.600000    45.800000   119.400000    37.000000    69.000000   

       WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
count   3344.000000   3344.000000  3335.000000  3334.000000  3334.000000   
mean      15.726555     21.242853    73.311724    90.768476  1004.605655   
std       18.970364     21.343298    75.170637   184.473679   116.988059   
min        0.000000      0.000000     1.000000     2.000000     0.000000   
25%       11.000000     15.000000    58.000000    44.000000  1013.400000   
50%       15.000000     20.000000    69.000000    56.000000  1018.350000   
75%       20.000000     24.000000    80.000000    66.000000  1023.000000   
max     1009.900000   1021.300000  1027.200000  1037.000000  1039.000000   

       Pressure3pm     Cloud9am     Cloud3pm      Temp9am      Temp3pm  \
count  3318.000000  3315.000000  3312.000000  3290.000000  2726.000000   
mean    971.011223     6.595958     7.536564    15.566717    21.138665   
std     208.465361     6.148958     7.405595     8.386873     6.032295   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%    1010.500000     2.000000     2.000000    11.500000    18.300000   
50%    1015.900000     6.000000     6.000000    16.900000    21.200000   
75%    1020.600000     8.000000     8.000000    21.200000    24.500000   
max    1036.700000    34.900000    57.400000   109.400000   105.800000   

           RISK_MM  
count  2621.000000  
mean      3.036627  
std       9.063623  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max     119.400000

In [55]:
np.sum(sydney.isnull())

Date              0
Location          0
MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          0
WindSpeed9am      0
WindSpeed3pm      0
Humidity9am       9
Humidity3pm      10
Pressure9am      10
Pressure3pm      26
Cloud9am         29
Cloud3pm         32
Temp9am          54
Temp3pm         618
RISK_MM         723
dtype: int64

In [56]:
sydney['Humidity9am'] = sydney['Humidity9am'].fillna((sydney['Humidity9am'].mean()))
sydney['Humidity3pm'] = sydney['Humidity3pm'].fillna((sydney['Humidity3pm'].mean()))
sydney['Pressure9am'] = sydney['Pressure9am'].fillna((sydney['Pressure9am'].mean()))
sydney['Pressure3pm'] = sydney['Pressure3pm'].fillna((sydney['Pressure3pm'].mean()))
sydney['Cloud9am'] = sydney['Cloud9am'].fillna((sydney['Cloud9am'].mean()))
sydney['Cloud3pm'] = sydney['Cloud3pm'].fillna((sydney['Cloud3pm'].mean()))
sydney['Temp9am'] = sydney['Temp9am'].fillna((sydney['Temp9am'].mean()))
sydney['Temp3pm'] = sydney['Temp3pm'].fillna((sydney['Temp3pm'].mean()))
sydney['RISK_MM'] = sydney['RISK_MM'].fillna((sydney['RISK_MM'].mean()))

np.sum(sydney.isnull())

Date            0
Location        0
MinTemp         0
MaxTemp         0
Rainfall        0
Evaporation     0
Sunshine        0
WindSpeed9am    0
WindSpeed3pm    0
Humidity9am     0
Humidity3pm     0
Pressure9am     0
Pressure3pm     0
Cloud9am        0
Cloud3pm        0
Temp9am         0
Temp3pm         0
RISK_MM         0
dtype: int64

In [57]:
from scipy import stats
sydney1=sydney.drop('Date',1)
sydney2=sydney1.drop('Location',1)
z = np.abs(stats.zscore(sydney2._get_numeric_data()))
print(z)
sydney = sydney[(z < 3).all(axis=1)]
print(sydney.shape)

[[1.0149566  0.12717085 1.24154843 ... 0.61715791 0.04382839 0.36937454]
 [1.0149566  0.5769373  0.26924683 ... 0.82154339 0.67236766 0.44416255]
 [1.47526306 0.33490013 0.33001568 ... 0.95379282 0.34181564 1.96485191]
 ...
 [1.19889827 1.1613297  0.33844167 ... 0.645223   0.70493244 0.37850547]
 [1.04546279 0.80927562 0.33844167 ... 0.38072414 0.39274442 0.37850547]
 [1.59344667 0.80927562 0.33844167 ... 0.7414044  0.42947242 0.37850547]]
(2990, 18)


In [64]:
sydney

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0       1/2/2008   Sydney     19.5     22.4      15.6          6.2       0.0   
1       2/2/2008   Sydney     19.5     25.6       6.0          3.4       2.7   
2       3/2/2008   Sydney     21.6     24.5       6.6          2.4       0.1   
5       6/2/2008   Sydney     20.2     27.2       1.6          2.6       8.6   
7       8/2/2008   Sydney     17.2     22.3      27.6          5.8       2.1   
8       9/2/2008   Sydney     16.4     20.8      12.6          4.8       3.0   
9      10/2/2008   Sydney     14.6     24.2       8.8          4.4      10.1   
10     11/2/2008   Sydney     16.4     23.9       0.0          6.4       8.0   
11     12/2/2008   Sydney     18.9     27.3       0.0          6.8       6.7   
12    13/02/2008   Sydney     18.4     22.8      14.4          7.0       3.3   
13    14/02/2008   Sydney     16.9     24.3       3.0          3.2       8.7   
14    15/02/2008   Sydney     18.3     24.4       0.0          6.2       8.5   
15    16/02/2008   Sydney     16.7     24.1       0.0          6.2       8.8   
16    17/02/2008   Sydney     19.5     24.8       0.0          7.6       3.2   
17    18/02/2008   Sydney     18.6     25.3       0.0          4.2       4.5   
18    19/02/2008   Sydney     19.0     24.8       0.0          5.2       7.5   
19    20/02/2008   Sydney     18.3     26.4       0.0          4.6      11.1   
20    21/02/2008   Sydney     20.6     26.8       0.0          6.8       6.4   
21    22/02/2008   Sydney     19.1     25.4       0.4          4.4       9.4   
22    23/02/2008   Sydney     20.5     26.0       0.0          6.6      12.2   
23    24/02/2008   Sydney     16.5     28.3       0.0          8.6      12.0   
24    25/02/2008   Sydney     20.5     24.2       0.0          8.6       1.5   
25    26/02/2008   Sydney     19.3     26.2       0.0          3.6       8.4   
26    27/02/2008   Sydney     19.0     29.0      22.2          8.2       3.3   
29      1/3/2008   Sydney     12.8     22.0       0.2          6.2      11.3   
30      2/3/2008   Sydney     14.2     23.4       5.4          6.4       7.3   
31      3/3/2008   Sydney     15.0     23.1       0.2          2.6      11.2   
32      4/3/2008   Sydney     15.5     25.4       0.0          6.8      11.3   
33      5/3/2008   Sydney     18.7     25.8       0.0          6.0       8.7   
34      6/3/2008   Sydney     19.6     26.0       0.0          5.0      10.4   
...          ...      ...      ...      ...       ...          ...       ...   
3309  22/05/2017   Sydney     13.0     21.0       0.0          1.0       6.9   
3310  23/05/2017   Sydney     14.7     22.6       0.0          2.4       8.8   
3311  24/05/2017   Sydney     14.8     22.7       0.8          3.4       9.0   
3312  25/05/2017   Sydney     11.6     21.4       0.0          5.6       9.6   
3313  26/05/2017   Sydney     10.6     20.8       0.0          1.8       9.8   
3314  27/05/2017   Sydney     12.6     20.6       0.0          2.8       7.0   
3315  28/05/2017   Sydney     11.9     23.7       0.0          2.4       8.4   
3316  29/05/2017   Sydney     11.4     18.3       0.0          5.2       9.4   
3317  30/05/2017   Sydney      7.1     17.1       0.0          3.4       9.7   
3318  31/05/2017   Sydney      9.7     16.3       0.0          3.4       7.8   
3319    1/6/2017   Sydney      8.0     18.3       0.0          4.8       9.7   
3320    2/6/2017   Sydney      8.5     18.1       0.0          3.2       4.8   
3321    3/6/2017   Sydney     10.7     17.4       0.0          3.4       2.1   
3322    4/6/2017   Sydney     10.5     19.7       1.4          0.6       6.8   
3323    5/6/2017   Sydney      9.4     19.6       0.0          2.8       9.4   
3329   11/6/2017   Sydney     12.5     17.2       2.8          1.6       0.2   
3330   12/6/2017   Sydney     11.3     20.4       1.2          0.8       7.5   
3331  13/06/2017   Sydney      9.5     18.7       0.0          2.2       9.1   
3332  14/06/

In [69]:
x = sydney.iloc[0:2991,2:18]
x.tail()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindSpeed9am  \
3339      8.6     19.6       0.0          2.0       7.8          22.0   
3340      9.3     19.2       0.0          2.0       9.2          20.0   
3341      9.4     17.7       0.0          2.4       2.7          15.0   
3342     10.1     19.3       0.0          1.4       9.3          17.0   
3343      7.6     19.3       0.0          3.4       9.4          13.0   

      WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  \
3339          20.0         73.0         52.0       1025.9       1025.3   
3340           7.0         78.0         53.0       1028.5       1024.6   
3341          13.0         85.0         56.0       1020.8       1015.0   
3342          19.0         56.0         35.0       1017.3       1015.1   
3343          13.0         73.0         32.0       1018.6       1015.4   

      Cloud9am  Cloud3pm  Temp9am  Temp3pm  RISK_MM  
3339       2.0       2.0     10.5     17.9      0.0  
3340       2.0       2.0     11.0     18.7      0.0  
3341       6.0       6.0     10.2     17.3      0.0  
3342       5.0       2.0     12.4     19.0      0.0  
3343       1.0       1.0      9.4     18.8      0.0

In [70]:
from sklearn.preprocessing import normalize
xnorm = normalize(x,norm='l2')
xnorm = pd.DataFrame(xnorm)
xnorm

0         1         2         3         4         5         6   \
0     0.013492  0.015498  0.010793  0.004290  0.000000  0.011762  0.013838   
1     0.013508  0.017733  0.004156  0.002355  0.001870  0.006234  0.009005   
2     0.014965  0.016975  0.004573  0.001663  0.000069  0.011778  0.001386   
3     0.014233  0.019165  0.001127  0.001832  0.006059  0.006341  0.015501   
4     0.012030  0.015597  0.019304  0.004057  0.001469  0.004896  0.010492   
5     0.011463  0.014538  0.008807  0.003355  0.002097  0.013280  0.006291   
6     0.010156  0.016833  0.006121  0.003061  0.007025  0.007652  0.013912   
7     0.011377  0.016580  0.000000  0.004440  0.005550  0.006243  0.018037   
8     0.013204  0.019072  0.000000  0.004751  0.004681  0.004890  0.016767   
9     0.012826  0.015893  0.010038  0.004879  0.002300  0.016729  0.020912   
10    0.011719  0.016851  0.002080  0.002219  0.006033  0.010402  0.013175   
11    0.012654  0.016872  0.000000  0.004287  0.005878  0.013138  0.015213   
12    0.011514  0.016616  0.000000  0.004275  0.006067  0.007584  0.017926   
13    0.013432  0.017083  0.000000  0.005235  0.002204  0.008955  0.016532   
14    0.012853  0.017482  0.000000  0.002902  0.003110  0.008983  0.016584   
15    0.013173  0.017194  0.000000  0.003605  0.005200  0.004853  0.011787   
16    0.012745  0.018387  0.000000  0.003204  0.007731  0.009054  0.015322   
17    0.014365  0.018689  0.000000  0.004742  0.004463  0.002789  0.010460   
18    0.013379  0.017792  0.000280  0.003082  0.006584  0.007705  0.019613   
19    0.014368  0.018223  0.000000  0.004626  0.008551  0.014018  0.016821   
20    0.011555  0.019819  0.000000  0.006023  0.008404  0.007704  0.016808   
21    0.014219  0.016786  0.000000  0.005965  0.001040  0.010404  0.013873   
22    0.013377  0.018160  0.000000  0.002495  0.005822  0.001386  0.019407   
23    0.013230  0.020194  0.015459  0.005710  0.002298  0.000000  0.010445   
24    0.008850  0.015211  0.000138  0.004287  0.007813  0.013137  0.021434   
25    0.009758  0.016080  0.003711  0.004398  0.005016  0.008933  0.011682   
26    0.010328  0.015905  0.000138  0.001790  0.007711  0.010328  0.013082   
27    0.010720  0.017567  0.000000  0.004703  0.007815  0.006225  0.013141   
28    0.012869  0.017755  0.000000  0.004129  0.005987  0.013075  0.015140   
29    0.013524  0.017940  0.000000  0.003450  0.007176  0.007590  0.013110   
...        ...       ...       ...       ...       ...       ...       ...   
2960  0.008955  0.014466  0.000000  0.000689  0.004753  0.011711  0.007578   
2961  0.010163  0.015624  0.000000  0.001659  0.006084  0.007605  0.011753   
2962  0.010301  0.015800  0.000557  0.002366  0.006264  0.004872  0.015312   
2963  0.008027  0.014808  0.000000  0.003875  0.006643  0.015223  0.007611   
2964  0.007329  0.014381  0.000000  0.001245  0.006776  0.013137  0.008988   
2965  0.008712  0.014244  0.000000  0.001936  0.004840  0.013138  0.010372   
2966  0.008301  0.016532  0.000000  0.001674  0.005859  0.009068  0.016741   
2967  0.007908  0.012695  0.000000  0.003607  0.006521  0.010406  0.013181   
2968  0.004907  0.011818  0.000000  0.002350  0.006704  0.011749  0.011749   
2969  0.006675  0.011218  0.000000  0.002340  0.005368  0.013764  0.019269   
2970  0.005473  0.012519  0.000000  0.003284  0.006636  0.019154  0.017786   
2971  0.005814  0.012381  0.000000  0.002189  0.003283  0.016417  0.013681   
2972  0.007328  0.011917  0.000000  0.002329  0.001438  0.013698  0.015067   
2973  0.007215  0.013537  0.000962  0.000412  0.004673  0.013743  0.011681   
2974  0.006481  0.013514  0.000000  0.001931  0.006481  0.013790  0.004827   
2975  0.008568  0.011790  0.001919  0.001097  0.000137  0.010282  0.004113   
2976  0.007774  0.014035  0.000826  0.000550  0.005160  0.010320  0.010320   
2977  0.006506  0.012806  0.000000  0.001507  0.006232  0.013696  0.015066   
2978  0.007596  0.012181  0.001779  0.001232  0.001985  0.008897  0.006159   
2979  0.007349  0.013804  0.000412

In [84]:
from sklearn.feature_selection import SelectKBest, chi2, f_regression
Xx = x.iloc[0:2991,2:14]
y = x.iloc[0:2991,15]
selector = SelectKBest(f_regression,k='all').fit(Xx,y)
X_new = selector.transform(Xx)
scores = selector.scores_
scores

array([2.00927445e+02, 1.57059156e+01, 4.35656551e+02, 1.05138441e+00,
       1.56188992e+00, 2.20226733e+02, 4.15064115e+02, 1.10147387e+00,
       1.33137746e-02, 1.58475606e+02, 1.71647962e+02, 2.08318132e+01])